inputs:
  name:
    description: 'Artifact name'
    default: 'github-pages'
  path:
    description: "Path to put the static assets"
    default: .

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ runner.temp }}/dlpages
    - shell: bash
      run: |
        mkdir -p "$INPUT_PATH"
        tar -xvf "$RUNNER_TEMP/dlpages/artifact.tar" -C "$INPUT_PATH"
      env:
        INPUT_PATH: ${{ inputs.path }}
